SemmDesk.Web/Controllers/ReportesController.cs
namespace SemmDesk.Web.Controllers
{
    using SemmDesk.DAL.Contexto;
    using SemmDesk.Web.Models;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;

    public class ReportesController : Controller
    {
        private readonly Modelo _db;

        public ReportesController()
        {
            this._db = new Modelo();
        }
        // GET: Reportes
        public ActionResult Index()
        {
            var lsTecnicos = _db.Tecnicos.ToList().OrderBy(t => t.Nombres);
            var lsCategorias = _db.Categorias.ToList().OrderByDescending(x => x.Descripcion);
            var lsSubCategorias = _db.SubCategorias.ToList().OrderByDescending(x => x.Descripcion);
            var lsEstados = _db.EstadoIncidencias.ToList().OrderByDescending(x => x.Descripcion);

            ViewData["lsTecnicos"] = new SelectList(lsTecnicos, "TecnicoId", "Nombres");
            ViewData["lsCategorias"] = new SelectList(lsCategorias, "CategoriaId", "Descripcion");
            ViewData["lsSubCategorias"] = new SelectList(lsSubCategorias, "SubCategoriaId", "Descripcion");
            ViewData["lsEstados"] = new SelectList(lsEstados, "EstadoIncidenciaId", "Descripcion");
            return View();
        }

        public ActionResult GetReport(QueryReportModel query)
        {
            if (query.FechaInicio ==null)
            {
                query.FechaInicio = Convert.ToDateTime("2020-01-01 00:00:00");
            }
            if (query.FechaFinal == null)
            {
                query.FechaFinal = DateTime.Now;
            }

            var FechaInicio = query.FechaInicio;
            var FechaFinal = query.FechaFinal.Value.AddDays(1);
            var CategoriaId = query.CategoriaId;
            var SubCategoriaId = query.SubCategoriaId;
            var TecnicoId = query.TecnicoId;
            var Estado = query.EstadoId;

            var rIncidencias = (from i in _db.Incidencias
                                join emp in _db.Empleados on i.EmpleadoId equals emp.Codigo
                                join d in _db.vDepartamentos on emp.DepartamentoId equals d.departam
                                //join tec in _db.Tecnicos on emp.Codigo equals tec.CodigoEmpleado
                                    where (i.FechaCreacion >= FechaInicio && i.FechaCreacion <= FechaFinal || FechaInicio == null || FechaFinal == null)
                                       && (i.TecnicoID == TecnicoId || TecnicoId == null)
                                       && (i.CategoriaID == CategoriaId || CategoriaId == null)
                                       && (i.SubCategoriaID == SubCategoriaId || SubCategoriaId == null)
                                       &&(i.EstadoIncidenciaID == Estado || Estado == null)
                                           
                                           select new {i.IncidenciaId, i.FechaCreacion, i.Descripcion, i.Categoria,
                                                        i.SubCategoria, i.Prioridade, i.EstadoIncidencia, i.Tecnico.Identificador, 
                                                        i.ComentarioCierre, i.FechaCierre, emp.Departamento, emp.Nombres, d.descrip
                                                      }).ToList().OrderByDescending(x => x.IncidenciaId);

            List<IncidenciaViewModel> lsIncidenciaViewModel = new List<IncidenciaViewModel>();
            foreach (var item in rIncidencias)
            {
                var incidencia = new IncidenciaViewModel()
                {
                    IncidenciaId = item.IncidenciaId,
                    FechaIncidencia = item.FechaCreacion,
                    Descripcion = item.Descripcion,
                    Departamento = item.descrip,
                    EmpleadoNombre = item.Nombres,
                    Categoria = item.Categoria.Descripcion,
                    SubCategoria = item.SubCategoria.Descripcion,
                    Prioridad = item.Prioridade.Descripcion,
                    Estado = item.EstadoIncidencia.Descripcion,
                    Tecnico = item.Identificador,
                    Comentario = item.ComentarioCierre,
                    FechaCierre = item.FechaCierre
                };
                lsIncidenciaViewModel.Add(incidencia);
            };

            return View(lsIncidenciaViewModel.OrderByDescending(x => x.IncidenciaId));
        }
       
    }
}

SemmDesk.Web/Views/Reportes/GetReport.cshtml
@model IEnumerable<SemmDesk.Web.Models.IncidenciaViewModel>
@{
    ViewBag.Title = "GetReport";
}
@*<button class="btn" onclick="exportExcel()">Exportar Excel</button>*@
<button> Regresar>
    </button>
<table id="tbDataMin" class="table table-hover table-separate table-sm table-head-custom table-checkable nowrap" cellspacing="0" width="100%" style="margin:0 !important">
    <thead>

        <tr>
            <th>@Html.Label("Incidencia")</th>
            <th>@Html.Label("Fecha")</th>
            <th>@Html.Label("Categoría")</th>
            <th>@Html.Label("SubCategoria")</th>
            <th>@Html.Label("Prioridad")</th>
            <th>@Html.Label("Detalle")</th>
            <th>@Html.Label("Departamento")</th>
            <th>@Html.Label("Usuario")</th>
            <th>@Html.Label("Estado")</th>
            <th>@Html.Label("Técnico")</th>
            <th>@Html.Label("Solución")</th>
            <th>@Html.Label("Fecha Cierre")</th>
        </tr>
    </thead>
  
    <tbody class="bg-white">
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.IncidenciaId)</td>
            <td>@Html.DisplayFor(modelItem => item.FechaIncidencia)</td>
            <td>@Html.DisplayFor(modelItem => item.Categoria)</td>
            <td>@Html.DisplayFor(modelItem => item.SubCategoria)</td>
            <td>@Html.DisplayFor(modelItem => item.Prioridad)</td>
            <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
            <td>@Html.DisplayFor(modelItem => item.Departamento)</td>
            <td>@Html.DisplayFor(modelItem => item.EmpleadoNombre)</td>
            <td>@Html.DisplayFor(modelItem => item.Estado)</td>
            <td>@Html.DisplayFor(modelItem => item.Tecnico)</td>
            <td>@Html.DisplayFor(modelItem => item.Comentario)</td>
            <td>@Html.DisplayFor(modelItem => item.FechaCierre)</td>
        </tr>
        }

    </tbody>

</table>

<script>
    function exportExcel() {
        $("#tbDataMin").table2excel({
            name: "Table2Excel",
            filename: "rIncidencias",
            fileext: ".xls"
        });
    }
</script>

SemmDesk.Web/Views/Reportes/Index.cshtml
@model SemmDesk.Web.Models.QueryReportModel
@{
    ViewBag.Title = "getReportByTecnicoID";
}
<br />
<br />

@using (Html.BeginForm("GetReport", "Reportes", FormMethod.Post))
{
    <div class="row">


    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Reporte por técnicos</h5>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-md-2">
                            <label>Fecha Inicial</label>
                            @Html.TextBoxFor(m => m.FechaInicio, new { type = "date", @class = "form-control" })
                        </div>

                        <div class="col-md-2">
                            <label>Fecha Final</label>
                            @Html.TextBoxFor(m => m.FechaFinal, new { type = "date", @class = "form-control" })
                        </div>

                        <div class="col-md-2">
                            @Html.Label("Categoría", htmlAttributes: new { @class = "control-label col-md-6" })
                            @Html.DropDownListFor(m => m.CategoriaId, (SelectList)ViewBag.lsCategorias, " ", htmlAttributes: new { @class = "form-control" })
                        </div>
                        <div class="col-md-2">
                            @Html.Label("SubCategoría", htmlAttributes: new { @class = "control-label col-md-8" })
                            @Html.DropDownListFor(m => m.SubCategoriaId, (SelectList)ViewBag.lsSubCategorias, " ", htmlAttributes: new { @class = "form-control" })
                        </div>
                        <div class="col-md-2">
                            @Html.Label("Técnico", htmlAttributes: new { @class = "control-label col-md-6" })
                            @Html.DropDownListFor(m => m.TecnicoId, (SelectList)ViewBag.lsTecnicos, " ", htmlAttributes: new { @class = "form-control" })
                        </div>

                        <div class="col-md-2">
                            @Html.Label("Estado", htmlAttributes: new { @class = "control-label col-md-6" })
                            @Html.DropDownListFor(m => m.EstadoId, (SelectList)ViewBag.lsEstados, " ", htmlAttributes: new { @class = "form-control" })
                        </div>

                    </div>
                    <br />
                    <div class="row">

                    </div>
                </div>
                <div class="card-footer">

                    <div class="row">
                        <div class="offset-4">
                            <div class="btn-group" role="group">
                                <button type="submit" name="btnReporte" class="btn bg-primary btn-sm"><span aria-hidden="true">Generar Reporte </span></button>
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

SemmDesk.Web/Views/Reportes/ReporteByTecnico.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "ReportEmployee";
}

<div>
    @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "yes", width = "1200px" })
</div>

SemmDesk.Web/Views/Reportes/ReporteTecnico.cshtml
@model SemmDesk.Web.Models.QueryReportModel
@{
    ViewBag.Title = "getReportByTecnicoID";
}
<br />
<br />

@using (Html.BeginForm("ReporteByTecnico", "Reportes", FormMethod.Post))
{
    <div class="row">


    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Reporte por técnicos</h5>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-md-3">
                            <label>Fecha Inicial</label>
                            @Html.TextBoxFor(m => m.FechaInicio, new { type = "date", @class = "form-control" })
                        </div>

                        <div class="col-md-3">
                            <label>Fecha Final</label>
                            @Html.TextBoxFor(m => m.FechaFinal, new { type = "date", @class = "form-control" })
                        </div>

                        <div class="col-md-3">
                            @Html.Label("Categoría", htmlAttributes: new { @class = "control-label col-md-6" })
                            @Html.DropDownListFor(m => m.CategoriaId, (SelectList)ViewBag.lsCategorias, "-- Seleccione una categoría --", htmlAttributes: new { @class = "form-control" })
                        </div>

                        <div class="col-md-3">
                            @Html.Label("Técnico", htmlAttributes: new { @class = "control-label col-md-6" })
                            @Html.DropDownListFor(m => m.TecnicoId, (SelectList)ViewBag.lsTecnicos, "-- Seleccione un Técnico --", htmlAttributes: new { @class = "form-control" })
                        </div>

                    </div>
                    <br />
                    <div class="row">

                    </div>
                </div>
                <div class="card-footer">

                    <div class="row">
                        <div class="offset-4">
                            <div class="btn-group" role="group">
                                <button type="submit" name="rPDF" class="btn bg-primary btn-sm"><span aria-hidden="true">Generar Reporte PDF</span></button>
                            </div>
                            <div class="btn-group" role="group">
                                <button type="button" id="rExcel" class="btn bg-primary btn-sm"><span aria-hidden="true">Generar Reporte EXCEL</span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#rExcel').click(function() {                
                
                $.ajax({
                    url: '/Reportes/ReporteExcel',
                    type: 'POST',
                    success: function () {
                        alert('vino del metodo');
                    }
                });
            })
        });
    </script>
}