SemmDesk.Web/Models/IncidenciaViewModel.cs
namespace SemmDesk.Web.Models
{
    using SemmDesk.Entities.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    public class IncidenciaViewModel
    {
        [Display(Name = "ID #")]
        public int IncidenciaId { get; set; }

        [Display(Name = "DESCRIPCIÓN")]
        public string Descripcion { get; set; }

        [Display(Name = "CATEGORÍA")]
        public int CategoriaId { get; set; }

        [Display(Name = "CATEGORÍA")]
        public string Categoria { get; set; }

        [Display(Name = "SUBCATEGORÍA")]
        public int SubCategoriaId { get; set; }

        [Display(Name = "SUBCATEGORÍA")]
        public string SubCategoria { get; set; }

        [Display(Name = "PRIORIDAD")]
        public int PrioridadId { get; set; }

        [Display(Name = "PRIORIDAD")]
        public string Prioridad { get; set; }

        [Display(Name = "ESTADO")]
        public int EstadoIncidenciaId { get; set; }

        [Display(Name = "ESTADO")]
        public string Estado { get; set; }

        [Display(Name = "EmpleadoID")]
        public int EmpleadoId { get; set; }

        [Display(Name = "Empleado")]
        public string EmpleadoNombre { get; set; }

        [Display(Name = "DEPARTAMENTO ID")]
        public int DepartamentoID { get; set; }

        [Display(Name = "DEPARTAMENTO")]
        public string Departamento { get; set; }

        [Display(Name = "TÉCNICO")]
        public int TecnicoId { get; set; }

        [Display(Name = "TÉCNICO")]
        public string Tecnico { get; set; }

        [Display(Name = "NOTA DE CIERRE")]
        public string Comentario { get; set; }

        //[Display(Name = "TÉCNICO REASIGNADO")]
        //public int? TecnicoReasignado { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:MM}")]
        [Display(Name = "FECHA")]
        [DataType(DataType.Date)]
        public DateTime FechaIncidencia { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:MM}")]
        [Display(Name = "CIERRE")]
        [DataType(DataType.Date)]
        public DateTime? FechaCierre { get; set; }

        public int UsuarioCreacion { get; set; }

        public int AreaId { get; set; }
        
        public string Area { get; set; }
        
        public Tecnico Tecnicos { get; set; }
        public Empleado Empleados { get; set; }

    }
}

SemmDesk.Web/Controllers/IncidenciasController.cs
using SemmDesk.BLL;
using SemmDesk.DAL.Contexto;
using SemmDesk.Entities.Models;
using SemmDesk.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SemmDesk.Web.Controllers
{
    public class IncidenciasController : Controller
    {
        private readonly IncidenciaBLL _incidenciasBLL;
        private readonly Modelo db;
        private readonly EmpleadoBLL _empleadosBLL;

        public IncidenciasController()
        {
            this._incidenciasBLL = new IncidenciaBLL();
            this._empleadosBLL = new EmpleadoBLL();
            this.db = new Modelo();

        }

        public ActionResult Index(DateTime? fechaInicio, DateTime? fechaFinal)
        {

            var empleado = (Empleado)Session["Usuario"];
            ViewData["IsTecnico"] = empleado.RolId;
            List<IncidenciaViewModel> list = new List<IncidenciaViewModel>();

            if (empleado.RolId == (int)EnumTecnicoRol.Usuario)
            {
                //TODO: Ahora el id de empleado es difernte para las incidencias, antes era el codigo del empleado.
                // Sigo usando el codigo para agregar en EmpleadoId de la incidencia o mando el Id de la tabla empleado
                // Como cambiarla a las incidencias anteriores? 

                var lsIncidencias = (from i in db.Incidencias
                                     join p in db.Prioridades
                                     on i.PrioridadID equals p.PrioridadId
                                     join e in db.EstadoIncidencias on
                                     i.EstadoIncidenciaID equals e.EstadoIncidenciaId
                                     join emp in db.Empleados on
                                     i.EmpleadoId equals emp.Codigo
                                     join t in db.Tecnicos on
                                     i.TecnicoID equals t.TecnicoId
                                     where i.TecnicoID == t.TecnicoId && i.UsuarioCreacion == empleado.Codigo
                                     select new
                                     {
                                         Incidencia = i.IncidenciaId,
                                         Fecha = i.FechaCreacion,
                                         Descripcion = i.Descripcion,
                                         Estado = e.Descripcion,
                                         Comentario = i.ComentarioCierre
                                     }
                               ).ToList();


                foreach (var item in lsIncidencias)
                {
                    IncidenciaViewModel newIncidencia = new IncidenciaViewModel
                    {
                        IncidenciaId = item.Incidencia,
                        FechaIncidencia = item.Fecha,
                        Descripcion = item.Descripcion,
                        Estado = item.Estado,
                        Comentario = item.Comentario,
                    };
                    list.Add(newIncidencia);
                };


                return View("IndexUsuario", list.OrderByDescending(x => x.IncidenciaId));
            }
            else
            {
                var lsIncidencias = (from i in db.Incidencias
                                     join p in db.Prioridades
                                     on i.PrioridadID equals p.PrioridadId
                                     join e in db.EstadoIncidencias 
                                     on i.EstadoIncidenciaID equals e.EstadoIncidenciaId
                                     join emp in db.Empleados on
                                     i.EmpleadoId equals emp.Codigo
                                     join t in db.Tecnicos on
                                     i.TecnicoID equals t.TecnicoId
                                     join s in db.SubCategorias on
                                     i.SubCategoriaID equals s.SubCategoriaId
                                     join a in db.Areas on
                                     i.AreaId equals a.AreaId
                                     where i.EmpleadoId == emp.Codigo || i.EmpleadoId == emp.EmpleadoId//i.TecnicoID == t.TecnicoId
                                     select new
                                     {
                                         Incidencia = i.IncidenciaId,
                                         Fecha = i.FechaCreacion,
                                         Descripcion = i.Descripcion,
                                         Prioridad = p.Descripcion,
                                         Categoria = i.Categoria.Descripcion,
                                         Subcategoria = i.SubCategoria.Descripcion,
                                         Estado = e.Descripcion,
                                         Empleado = emp.Nombres,
                                         Tecnico = t.Identificador,
                                         Comentario = i.ComentarioCierre,
                                         Area = a.NombreArea
                                     }
                               ).ToList();

                foreach (var item in lsIncidencias)
                {
                    IncidenciaViewModel newIncidencia = new IncidenciaViewModel
                    {                       
                        IncidenciaId = item.Incidencia,
                        FechaIncidencia = item.Fecha,
                        Descripcion = item.Descripcion,
                        Categoria = item.Categoria,
                        SubCategoria = item.Subcategoria,
                        Prioridad = item.Prioridad,
                        Estado = item.Estado,
                        EmpleadoNombre = item.Empleado,
                        Tecnico = item.Tecnico,
                        Comentario = item.Comentario,
                        Area = item.Area

                    };
                    list.Add(newIncidencia);
                };

                ViewData["Total"] = lsIncidencias.Count();
                ViewData["Abiertas"] = lsIncidencias.Count(x => x.Estado == "ABIERTA");
                ViewData["Cerradas"] = lsIncidencias.Count(x => x.Estado == "CERRADA");
                ViewData["Retrasadas"] = lsIncidencias.Count();

                var fn = Convert.ToDateTime(fechaFinal).Date;
                if (fechaInicio != null && fechaFinal != null)
                {
                    var inicio = fechaInicio.Value.AddDays(-1).ToString(); //fechaInicio.Value.ToString("yyyy/MM/dd");
                    var final = fechaFinal.Value.AddDays(1).ToString(); //.Value.ToString("yyyy/MM/dd");

                    //DateTime FechaFinal = Convert.ToDateTime(fechaFinal);
                    //FechaFinal = FechaFinal.AddDays(1);

                    var lista = list.OrderBy(x => x.IncidenciaId).Where(x => x.FechaIncidencia >= DateTime.Parse(inicio) && x.FechaIncidencia <= DateTime.Parse(final));
                    return View(lista);
                }
                fechaInicio = DateTime.Now;
                fechaFinal = DateTime.Now;

                return View(list.OrderByDescending(x => x.IncidenciaId));

            }

        }

        public ActionResult Crear()
        {
            #region Llenando ViewBags para mandar a la vista
            var lsDepartamentos = db.vDepartamentos.ToList().OrderBy(d => d.descrip);
            var lsCategorias = db.Categorias.ToList().OrderBy(c => c.Descripcion);
            var lsSubCategorias = db.SubCategorias.ToList().OrderBy(s => s.Descripcion);
            var lsPrioridades = db.Prioridades.ToList().OrderByDescending(x => x.Descripcion);
            var lsEmpleados = _empleadosBLL.GetAll(); //db.Empleados.ToList().Where(x => x.Estatus != "C" || x.Estatus != "E").OrderBy(u => u.Nombres);
            var lsTecnicos = db.Tecnicos.ToList().OrderBy(t => t.Nombres);
            var lsEstadoIncidencia = db.EstadoIncidencias.ToList().OrderBy(e => e.Descripcion);
            var lsAreas = db.Areas.ToList().OrderByDescending(e => e.NombreArea);

            ViewData["lsDepartamentos"] = new SelectList(lsDepartamentos, "departam", "descrip");
            ViewData["lsCategorias"] = new SelectList(lsCategorias, "CategoriaId", "Descripcion");
            ViewData["lsSubCategorias"] = new SelectList(lsSubCategorias, "SubCategoriaId", "Descripcion");
            ViewData["lsPrioridades"] = new SelectList(lsPrioridades, "PrioridadId", "Descripcion");
            ViewData["lsEmpleados"] = new SelectList(lsEmpleados, "Codigo", "Nombres");
            ViewData["lsTecnicos"] = new SelectList(lsTecnicos, "TecnicoId", "Nombres");
            ViewData["lsEstadoIncidencia"] = new SelectList(lsEstadoIncidencia, "EstadoIncidenciaId", "Descripcion");
            ViewBag.lsAreas = new SelectList(lsAreas, "AreaId", "NombreArea");

            #endregion

            //TODO Igual aqui con relacion a obtener c/u de las propiedades de Session[Usuario].RoilId
            var empleado = (Empleado)Session["Usuario"];
            Session["IsTecnico"] = empleado.EmpleadoId;

            if ((int)Session["IsTecnico"] == (int)EnumTecnicoRol.Usuario)
            {
                return View("_partialCrearUsuario");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(IncidenciaViewModel vm)
        {
            #region Llenando ViewBags para mandar a la vista
            var lsDepartamentos = db.vDepartamentos.ToList().OrderBy(d => d.descrip);
            var lsCategorias = db.Categorias.ToList().OrderBy(c => c.Descripcion);
            var lsSubCategorias = db.SubCategorias.ToList().OrderBy(s => s.Descripcion);
            var lsPrioridades = db.Prioridades.ToList();

SemmDesk.Web/Views/Incidencias/Crear.cshtml
@model SemmDesk.Web.Models.IncidenciaViewModel

@{
    ViewBag.Title = "Crear Incidencia";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group col-md-6">
                @Html.Label("Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("DepartamentoID", (SelectList)ViewBag.lsDepartamentos, "Seleccione un Departamento", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DepartamentoID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-6">
                @Html.Label("Empleado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("EmpleadoID", (SelectList)ViewBag.lsEmpleados, "Seleccione un usuario", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">

            <div class="form-group col-md-6">
                @Html.Label("Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("CategoriaId", (SelectList)ViewBag.lsCategorias, "Seleccione una Categoria", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-6">
                @Html.Label("SubCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("SubCategoriaId", (SelectList)ViewBag.lsSubCategorias, "Seleccione una SubCategoria", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div class="row">
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Descripcion, htmlAttributes: new { @class = "form-control col-md-12", @cols = "12" })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                @Html.Label("Prioridad", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("Prioridadid", (SelectList)ViewBag.lsPrioridades, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PrioridadId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-6">
                @Html.Label("Estado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("EstadoIncidenciaId", (SelectList)ViewBag.lsEstadoIncidencia, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div class="row">
            <div class="form-group col-md-6">
                @Html.Label("Técnico", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownList("TecnicoId", (SelectList)ViewBag.lsTecnicos, " ", htmlAttributes: new { @class = "form-control", @placeholder = "Escoja un tecnico" })
                    @*@Html.EditorFor(model => model.TecnicoID, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.TecnicoId, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group col-md-6 ">
                @Html.Label("Area de Incidencia", htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-8">
                    @Html.DropDownList("AreaId", (SelectList)ViewBag.lsAreas, htmlAttributes: new { @class = "form-control", @placeholder = "Escoja el area de trabajo" })
                    @Html.ValidationMessageFor(model => model.AreaId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                @Html.Label("Nota de Cierre", htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Comentario, htmlAttributes: new { @class = "form-control ", @cols = "12" })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

    </div>

    <div class="row">
        <div class="offset-9">
            <div class="btn-group col-md-3" role="group">
                <button type="submit" class="btn bg-primary btn-sm"><span aria-hidden="true">Grabar</span></button>
            </div>
        </div>
    </div>
}
<br />

<div class="row">

    @Html.ActionLink("Regresar", "Index", "", new { @class = "btn" })

</div>

<script type="text/javascript" src="~/Content/plugins/jquery/jquery.min.js"></script>
<script>

    $(document).ready(function () {

        $("#CategoriaId").change(function () {
            //$.get("/Incidencias/ListaSubCategorias", { id: $("#CategoriaId").val() }, function (data) {
                $.get("/HelpDesk/Incidencias/ListaSubCategorias", { id: $("#CategoriaId").val() }, function (data) {
                $("#SubCategoriaId").empty();
                $.each(data, function (index, row) {
                    $("#SubCategoriaId").append("<option value='" + row.SubCategoriaId + "'>" + row.Descripcion + "</option>")
                });
            });
        });

        $("#DepartamentoID").change(function () {
            $.get("/HelpDesk/Incidencias/ListaEmpleados", { id: $("#DepartamentoID").val() }, function (data) {
            //$.get("/Incidencias/ListaEmpleados", { id: $("#DepartamentoID").val() }, function (data) {
                $("#EmpleadoID").empty();
                $.each(data, function (index, row) {
                    $("#EmpleadoID").append("<option value='" + row.Codigo + "'>" + row.Nombres + row.Apellido1 + "</option>")
                });
            });
        });

        //$("#EstadoIncidenciaId").change(function () {
        //    var valor = document.getElementById('EstadoIncidenciaId').value;
        //    if (valor != 2) {
        //        $('#TecnicoAsignadoId').hide();

        //    } else {
        //        $('#TecnicoAsignadoId').show();
        //    }
        //});
    });
</script>

SemmDesk.Web/Views/Incidencias/Index.cshtml
@model IEnumerable<SemmDesk.Web.Models.IncidenciaViewModel>

@{
    ViewBag.Title = "Lista Incidencias";
}

<!-- #region Para agregar filtro por fecha en el index NO ME PARECE MUY NECESARIO AUN -->

@*<div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">


    @using (Html.BeginForm("Index", "Incidencias"))
    {
        <div class="row">
            <div class="col-md-5">
                <input type="date" class="col-md-6 form-control" name="fechaInicio" />
            </div>
            <div class="col-md-5">
                <input type="date" class="col-md-6 form-control" name="fechaFinal" />
            </div>
            <button type="submit" class="btn">Filtrar </button>
        </div>
    }

</div>*@

<!-- #endregion -->

<div class="row">
    <div class="col-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light pl-0 pr-0">
            <div class="container-fluid p-0">
                <a class="navbar-brand" href="#">Incidencias</a>
                <span class="navbar-text pl-2 border-left"></span>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div id="filtro" class="form-inline ml-3" style="border: 1px solid #d8d8d8; border-radius: 5px;">
                        <div class="input-group input-group-sm">
                            <input id="global_filter" class="form-control form-control-navbar global_filter" type="search" placeholder="Buscar..." aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search fa-fw"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div id="dv_export" class="me-auto ml-2 mb-2 mb-lg-0">
                    </div>
                    <div class="ml-auto">
                        <a href="~/Incidencias/Crear" @*onclick="showInPopup('/Incidencias/Crear', '<i class=\'fas fa-building\'></i>&nbsp;Nueva incidencia')"*@
                           class="text-dark"><i class="fas fa-plus"></i>Nueva incidencia</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card card-dark card-outline">
            <div class="card-body p-0">
                <div class="mailbox-controls d-none">
                    <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                        <i class="far fa-square"></i>
                    </button>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-sm">
                            <i class="far fa-trash-alt"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm">
                            <i class="fas fa-reply"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm">
                            <i class="fas fa-share"></i>
                        </button>
                    </div>
                    <button type="button" class="btn btn-default btn-sm">
                        <i class="fas fa-sync-alt"></i>
                    </button>
                    <div class="float-right">

                    </div>
                </div>
                <table id="tbDataMin" class="table table-hover table-separate table-sm table-head-custom table-checkable nowrap" cellspacing="0" width="100%" style="margin:0 !important">
                    <thead>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.IncidenciaId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaIncidencia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Categoria)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SubCategoria)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Prioridad)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>


                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.EmpleadoNombre)
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.Tecnico)
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.Comentario)
                            </th>

                            <th></th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.IncidenciaId)</th>
                            <th>@Html.DisplayNameFor(model => model.FechaIncidencia)</th>
                            <th>@Html.DisplayNameFor(model => model.Categoria)</th>
                            <th>@Html.DisplayNameFor(model => model.SubCategoria)</th>
                            <th>@Html.DisplayNameFor(model => model.Prioridad)</th>
                            <th>@Html.DisplayNameFor(model => model.Descripcion)</th>

                            <th>@Html.DisplayNameFor(model => model.Estado)</th>
                            <th> @Html.DisplayNameFor(model => model.EmpleadoNombre)</th>
                            <th> @Html.DisplayNameFor(model => model.Tecnico)</th>
                            <th> @Html.DisplayNameFor(model => model.Comentario)</th>
                            <th></th>

                        </tr>
                    </tfoot>
                    <tbody class="bg-white">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IncidenciaId)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaIncidencia)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Categoria)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SubCategoria)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Prioridad)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                </td>
                                <td id="Estado">
                                    @Html.DisplayFor(modelItem => item.Estado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmpleadoNombre)
                                </td>

                                <td>
                                    @if (ViewData["IsTecnico"] != null)
                                    {
                                        @Html.DisplayFor(modelItem => item.Tecnico)
                                    }
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Comentario)
                                </td>


                                <td style="width:2%">
                                    <a href="@Url.Action("Editar","Incidencias", new {id = item.IncidenciaId})"> <i class="fas fa-edit"></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
            </div>
            <div class="card-footer p-0">
                <div class="mailbox-controls">
                    <div id="info" class="float-left p-1"></div>
                    <div id="pagination" class="float-right"></div>
                </div>
            </div>
        </div>

    </div>
</div>


@section Scripts{
    <script>
        $(document).ready(function () {
            // $('#dataTable').DataTable();
            var tdEstado = $('#tbDataMin td:nth-child(6)');

            for (var i = 0; i < tdEstado.length; i++) {

                if (tdEstado[i]['innerText'] == 'ABIERTA') {
                    tdEstado[i]['className'] = 'text-danger';
                }
                else if (tdEstado[i]['innerText'] == 'CERRADA') {
                    tdEstado[i]['className'] = 'text-success';
                }
            }

        });
    </script>
}